# Generated by Django 2.0.3 on 2018-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_auto_20180602_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='patan', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
