# Generated by Django 2.0.3 on 2018-06-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_auto_20180603_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emailid',
            new_name='email',
        ),
    ]
