# Generated by Django 2.0.3 on 2018-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_auto_20180603_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(default=0.29473684210526313),
        ),
    ]
