# Generated by Django 2.0.3 on 2018-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_auto_20180603_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=0.005614035087719298),
        ),
    ]
