# Generated by Django 2.0.3 on 2018-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_auto_20180603_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='patna', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(default='1-1-2019'),
        ),
    ]
