# Generated by Django 2.0.3 on 2018-06-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_auto_20180603_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
    ]
